# Generated by Django 4.0.1 on 2022-02-14 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_alter_person_address'),
        ('establishment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='establishment_address', to='person.address'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='establishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_establishment', to='person.person'),
        ),
    ]
