# Generated by Django 4.0.1 on 2022-02-01 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_address_lat_alter_address_lon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='address',
            new_name='addresses',
        ),
    ]
