# Generated by Django 4.0.1 on 2022-02-01 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_rename_address_person_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='addresses',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.address'),
        ),
    ]
