# Generated by Django 4.0.1 on 2022-02-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_remove_person_addresses_person_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='number',
            field=models.CharField(default='empty', max_length=120),
        ),
    ]
